### ISSUE TITLE
Pull Title and artist name from SoundCloud card and create a search result for youtube

### ISSUE THREAD

**Issue by TristanM225** [itsa-me-dea/FindYourMuse#12]
Pull the song title and artist name from the SoundCloud API to be used as search terms in the YouTube API. These will be applied to the YouTube API to find a related link.

**Comment by itsa-me-dea** [comment]
Pull the song title and artist name from the SoundCloud API to be used as search terms in the YouTube API. These will be applied to the YouTube API to find a related link.

**Comment by itsa-me-dea** [comment]
Completed in PR (Created the YouTube search function #25) by @TristanM225
