### ISSUE TITLE
Integrate youtube search result into a button

### ISSUE THREAD

**Issue by TristanM225** [itsa-me-dea/FindYourMuse#13]
Create a `button` (or `a`) DOM element with the YouTube icon image with a `href`/link to the related YouTube link (pulled from YouTube API)

**Comment by itsa-me-dea** [comment]
Create a `button` (or `a`) DOM element with the YouTube icon image with a href/link to the related YouTube link (pulled from YouTube API)

**Comment by itsa-me-dea** [comment]
Completed in PR (Created the YouTube search function #25) by @TristanM225
