### ISSUE TITLE
Create “genre” drop down in HTML

### ISSUE THREAD

**Issue by TristanM225** [itsa-me-dea/FindYourMuse#4]
## Genre 
Create a drop down of genres to chose from
Add drop down selection functionality (JS) for “genre”

**Comment by itsa-me-dea** [comment]
Added with "added JS for Mood and genre #18" PR by @TristanM225

**Comment by itsa-me-dea** [comment]
Added with "added JS for Mood and genre #18" PR by @TristanM225
